FROM node:20-alpine

# Install OpenSSL for Prisma and tzdata for timezone
RUN apk add --no-cache openssl tzdata

# Set timezone to Brazil
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
